/**
 * Bank Data Configuration
 * Contains list of banks and branches for dropdown selection
 */

// Unique branches (Police Stations/Locations)
export const branches = [
  "AS Nagar",
  "Akonduru",
  "Bhavanipuram",
  "Chandarlapadu",
  "Chillakollu",
  "Gampalagudem",
  "Gkonduru",
  "Governorpet",
  "Gunadala",
  "I Town",
  "II Town",
  "Ibrahimpatnam",
  "Jaggayyapet",
  "Kanchikacherla",
  "Krishna Lanka",
  "Machavaram",
  "Mahila PS",
  "Mylavaram",
  "Nandigama",
  "Nunna",
  "Patamata",
  "Penamaluru",
  "Penuganchiprolu",
  "Reddygudem",
  "SNPuram",
  "SR pet",
  "Suryaraopet",
  "Tiruvuru",
  "Vatsavai",
  "Veerulapadu",
  "Vissannapet"
].sort();

// Unique bank names
export const bankNames = [
  "ANDHRA BANK",
  "APCOB",
  "Axis Bank",
  "Bandhan Bank",
  "Bank of baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "CANARA BANK",
  "CENRAL BANKOF INDIA",
  "City Union Bank",
  "COASTAL BANK",
  "DBS Bank of India",
  "DHANALAKSHMI BANK",
  "Federal bank",
  "FEDERAL BANK",
  "Gandhi Co-Operative Bank",
  "GANDHI COOPERATIVE BANK",
  "Godavari Krishna Co Op Society LTD",
  "HDFC Bank",
  "ICICI BANK",
  "IDBI BANK",
  "IDFC BANK",
  "INDIAN BANK",
  "INDIAN OVERSEAS BANK",
  "Indus Ind Bank",
  "KANAKA MAHA LAKSHMI CO-OPERATIVE BANK",
  "Karur Vysya Bank",
  "KDCC Bank",
  "kotak Mahindra Bank",
  "MAHESH CO-OP BANK",
  "Panjab National Bank",
  "RBL BANK",
  "Repco Bank",
  "Saptagiri Grameena Bank",
  "SBI",
  "South Indian Bank",
  "State Co-operative Bank",
  "Tamilnad Mercantile Bank",
  "THE GANDHI CO-OPERATIVE URBAN BANK",
  "The Durga Co-operative Bank",
  "The krishna district co-oparative central bank (KDCC)",
  "UCO BANK",
  "union bank",
  "VIJAYA BANK",
  "YES BANK"
].sort();
